# =================================================================
# NETLIFY CONFIGURATION - Afrimercato Frontend
# =================================================================

[build]
  # Build command
  command = "npm run build"

  # Publish directory (Vite outputs to 'dist')
  publish = "dist"

  # Node version
  [build.environment]
    NODE_VERSION = "18"

# =================================================================
# ENVIRONMENT VARIABLES FOR PRODUCTION
# =================================================================
[context.production.environment]
  VITE_API_URL = "https://afrimercato-backend-production-0329.up.railway.app/api"
  VITE_APP_NAME = "Afrimercato"
  VITE_APP_VERSION = "1.0.0"

# =================================================================
# ENVIRONMENT VARIABLES FOR PREVIEW/BRANCH DEPLOYS
# =================================================================
[context.deploy-preview.environment]
  VITE_API_URL = "https://afrimercato-backend-production-0329.up.railway.app/api"

[context.branch-deploy.environment]
  VITE_API_URL = "https://afrimercato-backend-production-0329.up.railway.app/api"

# =================================================================
# REDIRECTS & REWRITES (For React Router)
# =================================================================
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# =================================================================
# HEADERS (Security & Performance)
# =================================================================
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
